Document: bloonix-plugins-mysql
Title: Debian bloonix-plugins-mysql Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-mysql is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-mysql/bloonix-plugins-mysql.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-mysql/bloonix-plugins-mysql.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-mysql/bloonix-plugins-mysql.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-mysql/html/index.html
Files: /usr/share/doc/bloonix-plugins-mysql/html/*.html


